// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestWithASPNETUdemy.Data;

#nullable disable

namespace RestWithASPNETUdemy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220719195948_BooksSeeding")]
    partial class BooksSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestWithASPNETUdemy.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Michael C. Feathers",
                            LaunchDate = new DateTime(2017, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 49.0,
                            Title = "Working effectively with legacy code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ralph Johnson, Erich Gamma, John Vlissides e Richard Helm",
                            LaunchDate = new DateTime(2017, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert C. Martin",
                            LaunchDate = new DateTime(2009, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 56.0,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Crockford",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 67.0,
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Steve McConnell",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 58.0,
                            Title = "Code complete"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Martin Fowler e Kent Beck",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 88.0,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Eric Freeman, Elisabeth Freeman, Kathy Sierra, Bert Bates",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 110.0,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eric Evans",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 92.0,
                            Title = "Domain Driven Design"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Brian Goetz e Tim Peierls",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 80.0,
                            Title = "Java Concurrency in Practice"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Susan Cain",
                            LaunchDate = new DateTime(2017, 11, 7, 15, 9, 1, 674, DateTimeKind.Unspecified),
                            Price = 123.0,
                            Title = "O poder dos quietos"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Roger S. Pressman",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 56.0,
                            Title = "Engenharia de Software: uma abordagem profissional"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Viktor Mayer-Schonberger e Kenneth Kukier",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 54.0,
                            Title = "Big Data: como extrair volume, variedade, velocidade e valor da avalanche de informação cotidiana"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Richard Hunter e George Westerman",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 95.0,
                            Title = "O verdadeiro valor de TI"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Marc J. Schiller",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0,
                            Title = "Os 11 segredos de líderes de TI altamente influentes"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Aguinaldo Aragon Fernandes e Vladimir Ferraz de Abreu",
                            LaunchDate = new DateTime(2017, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 54.0,
                            Title = "Implantando a governança de TI"
                        });
                });

            modelBuilder.Entity("RestWithASPNETUdemy.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Curitiba - PR",
                            FirstName = "João",
                            Gender = "Male",
                            LastName = "Vitor"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Anchiano - Italy",
                            FirstName = "Leonardo",
                            Gender = "Male",
                            LastName = "Da Vinci"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Porbandar - India",
                            FirstName = "Mahatma",
                            Gender = "Male",
                            LastName = "Gandhi"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kentucky - USA",
                            FirstName = "Mohamed Ali",
                            Gender = "Male",
                            LastName = "Gandhi"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Mvezo - South Africa",
                            FirstName = "Nelson",
                            Gender = "Male",
                            LastName = "Mandela"
                        },
                        new
                        {
                            Id = 6,
                            Address = "New England",
                            FirstName = "Vitoria",
                            Gender = "Female",
                            LastName = "Elizabeth"
                        },
                        new
                        {
                            Id = 7,
                            Address = "São Paulo - Brasil",
                            FirstName = "Ayrton",
                            Gender = "Male",
                            LastName = "Senna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
